const ActionTypes = {
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  GET_ACCOUNT_LIST: 'GET_ACCOUNT_LIST',
  GET_COUNTRY_DATA: 'GET_COUNTRY_DATA',
  FETCH_DATA_ERROR: 'FETCH_DATA_ERROR',
  FETCH_DATA_LOADING: 'FETCH_DATA_LOADING',
  FETCH_CREATE_ERROR: 'FETCH_CREATE_ERROR',
};
export default ActionTypes;
