const ActionTypes = {
  GET_ACCOUNT_LIST: 'GET_ACCOUNT_LIST',
  GET_COUNTRY_DATA: 'GET_COUNTRY_DATA',
  FETCH_DATA_ERROR: 'FETCH_DATA_ERROR',
  FETCH_DATA_LOADING: 'FETCH_DATA_LOADING',
};
export default ActionTypes;
