const ActionTypes = {
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  GET_ACCOUNT_LIST: 'GET_ACCOUNT_LIST',
  FETCH_DATA_ERROR: 'FETCH_DATA_ERROR',
  FETCH_DATA_LOADING: 'FETCH_DATA_LOADING',
};
export default ActionTypes;
